config/routes.rb
Rails.application.routes.draw do
  root to: 'pictures#top'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :pictures do
    collection do   # idなどを必要としない固有のルーティング
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user

  validates :title, presence: true, length: { in: 1..140 }
  validates :content, presence: true, length: { in: 1..140 }
  validates :user_id, presence: true
  validates :photo, presence: true

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user

  validates :content, presence: true, length: { in: 1..140 }
  validates :user_id, presence: true
  validates :photo, presence: true

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, ImageUploader

  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :icon, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def require_user_logged_in
    unless logged_in?
      flash[:danger] = 'ログインしてください'
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(picture_id: params[:picture_id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController # < で継承している
  before_action :require_user_logged_in, only: [:index, :new, :edit, :show]
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def top
  end

  def index
    @pictures = Picture.all.order(id: "DESC")
    #binding.pry # pry-railsでブレークポイントを設定して、デバッグ
    #raise # better_errorsでエラー画面を出力させる
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
      # 画像保存（create）の際に、キャッシュから画像を復元してから保存する
      @picture.photo.retrieve_from_cache! params[:cache][:photo] if params[:cache][:photo].present?
    else
      @picture = Picture.new  #ビューにデータを渡す(インスタンス変数を定義する)
    end
  end

  def create
    # @picture = Picture.new(picture_params)
    # @picture.user_id = current_user.id
    # 下記の1行は、上記の2行をまとめて記述している
    @picture = current_user.pictures.build(picture_params)

    # 画像保存（create）の際に、キャッシュから画像を復元してから保存する
    @picture.photo.retrieve_from_cache! params[:cache][:photo] if params[:cache][:photo].present?

    # binding.pry
    if @picture.save
      @user = User.find_by(id: current_user.id)
      ContactMailer.contact_mail(@user,@picture).deliver # 追記 メール送信処理
      # 一覧画面へ遷移して"投稿を作成しました！"とメッセージを表示します。
      flash[:success] = '投稿を作成しました！'
      redirect_to pictures_path
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def show
    # @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      flash[:success] = '投稿を編集しました！'
      redirect_to pictures_path
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    flash[:success] = '投稿を削除しました！'
    redirect_to pictures_path
  end

  def confirm
    # render :new if @picture.invalid?
    @picture = Picture.new(picture_params)
    @picture[:user_id] = current_user.id
    render :new if @picture.invalid? # <=バリデーションチェックNGなら戻す
  end

  private
  def picture_params
    params.require(:picture).permit(:content, :photo, :photo_cache)
  end

  # idをキーとして値を取得するメソッド
  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id # session idの発行（デフォルトではCookie)
      flash[:success] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_pictures = @user.favorite_pictures.order(id: "DESC")
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:icon, :icon_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    # @current_user || @current_user = User.find_by(id: session[:user_id])と以下のコードは同じ
    @current_user ||= User.find_by(id: session[:user_id])
    # @current_userが真の場合はそのままにし、偽の場合は右辺の値 User.find_by(id: session[:user_id]) を代入するというもの
  end

  def logged_in?
    # current_user.nil? だと、「current_userがnilの場合（ログインしていない場合）にtrue」を返すが、
    # 先頭に ! をつけると逆になり「current_userがnilではない場合（ログインしている場合）にtrue」を返す
    !current_user.nil?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/top.html.erb
<div class="top_img">
  <img src="images/top.jpg"/>
  <p>
    下村さんのBlog
  </p>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">  <!-- head内にこのタグ設定を追記する -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">ホーム</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ホーム</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/pictures">投稿一覧</a></li>
            <li><a href="/pictures/new">新規投稿</a></li>
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <%= yield %>

    </div>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>

<% if @picture.errors.any? %>
  <div class="alert alert-warning">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="row mb_20">
    <%= form.label :content, class: 'col-sm-2' %>
    <%= form.text_field :content, class: 'col-sm-10' %>
  </div>
  <div class="row mb_20">
    <%= form.label :photo, class: 'col-sm-2' %>
    <%= form.file_field :photo, id: :picture_photo, class: 'col-sm-10' %>
    <!-- バリデーションで引っかかった時用の処理 -->
    <%= form.hidden_field :photo_cache %>
  </div>
  <div class="row center">
    <%= form.submit :class => "square_btn" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h1>以下の内容で、送信する。</h1>

<%= form_with(model: @picture, local: true, url: pictures_path) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :photo, id: :picture_photo %>

  <div class="row mb_20">
    <div class="col-sm-2">内容</div>
    <div class="col-sm-10"><%= @picture.content %></div>
  </div>
  <div class="row mb_20">
    <div class="col-sm-2">画像</div>
    <div class="col-sm-10"><%=image_tag(@picture.photo.url) %></div>
    <%= hidden_field_tag :"cache[photo]", @picture.photo.cache_name %>
  </div>
  <div class="row center mb20 pb_10">
    <%= form.submit "登録する", class:'btn btn-success' %>
  </div>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :photo, id: :picture_photo %>
  <%= hidden_field_tag :"cache[photo]", @picture.photo.cache_name %>
  <div class="row center">
  <%= form.submit "もどる", name: 'back', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>ブログを編集する</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<%= render 'layouts/flash_messages' %>

<% if @pictures %>
<div class="row center">
  <% @pictures.each do |picture| %>
    <div class="col-xs-12 col-md-12 picture-panel mb_50">

      <p><%= picture.user.name %>さんの投稿</p>
      <p><%=image_tag picture.photo %></p>
      <p><%= picture.content %></p>
      <p><%= picture.updated_at %></p>


      <div class="picture-links">
        <%= link_to '詳細', picture_path(picture.id), class: 'btn btn-default' %>
        <% if picture.user == current_user %>
          <%= link_to '編集', edit_picture_path(picture.id), class: 'btn btn-info' %>
          <%= link_to '削除', picture_path(picture.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/pictures/new.html.erb
<h1>画像・内容を投稿する</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>

<div class="row">
  <div class="col-sm-2">内容</div>
  <div class="col-sm-10"><%= @picture.content %></div>
</div>
<div class="row">
  <div class="col-sm-2">画像</div>
  <div class="col-sm-10"><%=image_tag @picture.photo %></div>
</div>

<% unless @picture.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(picture_id: @picture.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/pictures/top.html.erb
<div class="top_img">
  <img src="images/top.jpg"/>
  <p>
    下村さんの Instagram Clone
  </p>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <div class="row mb_20">
    <%= f.label :name, class: 'col-sm-2' %>
    <%= f.text_field :name, class: 'col-sm-10' %>
  </div>

  <div class="row mb_20">
    <%= f.label :email, class: 'col-sm-2' %>
    <%= f.email_field :email, class: 'col-sm-10' %>
  </div>

  <div class="row mb_20">
    <%= f.label :password, class: 'col-sm-2' %>
    <%= f.password_field :password, class: 'col-sm-10' %>
  </div>

  <div class="row mb_20">
    <%= f.label :password_confirmation, class: 'col-sm-2'  %>
    <%= f.password_field :password_confirmation, class: 'col-sm-10'  %>
  </div>

  <div class="row mb_20">
    <%= f.label :icon, class: 'col-sm-2' %>
    <%= f.file_field :icon, id: :user_icon, class: 'col-sm-10' %>
    <!-- バリデーションで引っかかった時用の処理 -->
    <%= f.hidden_field :icon_cache %>
  </div>

  <div class="row center">
    <%= f.submit "Create my account", class: "square_btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/flash_messages' %>

<h1 class="center"><%= @user.name %>さんのページ</h1>

<div class="row center">
  <div class="col-sm-12"><%= @user.email %></div>
  <div class="col-sm-12"><%=image_tag @user.icon.thumb %></div>
</div>

<hr>

<h2 class="center"><%= @user.name %>のお気に入り一覧</h2>
<% if @favorite_pictures %>

<div class="row center">
  <% @favorite_pictures.each do |picture| %>
    <div class="col-xs-12 col-md-12 picture-panel mb_30">
      <p><%= picture.user.name %>さんの投稿</p>
      <p><%=image_tag picture.photo %></p>
      <p><%= picture.content %></p>
      <p><%= picture.updated_at %></p>
    </div>
  <% end %>
</div>

<% end %>